matrix:
  include:
    - env: TAG=5.6
    - env: TAG=7.0
    - env: TAG=7.1
    - env: TAG=7.2
    - env: TAG=7.2-codecasts
    - env: TAG=7.3-codecasts

services:
  - docker

cache:
  directories:
    - files/s6-overlay

script:
  - make build TAG=$(printenv TAG)
  - make run TAG=$(printenv TAG)
  - sleep 15 # Wait for the docker health check to complete
  - make test TAG=$(printenv TAG)

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u="existenz" -p="$DOCKER_PASSWORD";
    docker push existenz/webstack;
    fi
