matrix:
  include:
    - env: TAG=5.6
    - env: TAG=7.0
    - env: TAG=7.1
    - env: TAG=7.2
    - env: TAG=7.3
    - env: TAG=7.2-codecasts
    - env: TAG=7.3-codecasts
    - env: TAG=7.4-codecasts
  allow_failures:
    - env: TAG=7.4-codecasts

services:
  - docker

cache:
  directories:
    - files/s6-overlay

script:
  - make build TAG=$(printenv TAG)
  - make run TAG=$(printenv TAG)
  - sleep 15 # Wait for the docker health check to complete
  - make test TAG=$(printenv TAG)

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u="existenz" -p="$DOCKER_PASSWORD";
    docker push existenz/webstack;
    fi

notifications:
  webhooks:
    urls:
      - secure: "YjbuPvfJwW5r+uhvN5b+E5/QWo/wmv5OUpvCt07pqZw0ccZwxxNxsQmBW2jx+yA0vDZkHRS0hG4sYJmkGG7zdfWx0w64VDfykueE92ow7DCugIpRGWeXKaQyo9Yv0F0/2gwEzwOIje/rArZ9WORhmZ61hKkHkfbog/FchG5j5rLt7tf0+60xQ2dXZko21ytb8eR/YE3UN8iGOVhEkYxrCWaW54IDYDXq1o475YBDMOgPjrCglttazR2sLAPVGgXC1/wT+H0F5kex7zIX3SdTlSnjH2QgqwB6DTFDVMcfC6LOJjxra9Dl1HnuPY0nBplYDo1xqZr+X9jMRyaHqlMHYnlifxfLrqHT0o/DNcxpGYQ/hUXbzt/b5JGuk4YForwfoEROqmprcpFdLkDNluEX+f8qQVf1dVVckK9zBL7d3NY5Y3cee4EpjylUj9sxaFlfCPypFvi2syFdmuN3WgPvHZmws9FxuxkIwduElfRfDN3g4NXEHPzcL8HYIx9lKZ5lrx5xUsAk2bTvZC404bNcL7Igacfm3n945W7+QN+Bni61zItkKshc6Si7ra0J2J862SZtJbb1a8HG+QpNmw162YNnvH3cUABhq2IQeUq5eKepQVzYzuIkrgWE+hZ++Lnv2N8W1sAyU8SKeQ3HC8+peAjvlz0xmtCMIXhH89UZpqQ="
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
